FROM node:20-alpine

WORKDIR /app

# System dependency for Prisma engine
RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm install

# Copy prisma schema so we can generate client
COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "dev"]
